model:
  stage_1:
    text_features:
      - "Список навыков"
      - "prof_field_full"
    cluster_match_features:
      - "Должность_cat_sim"
      - "Должность_subcat_sim"
    weights: [1.0, 1.0, 1.0, 1.0]
    top_n: 100
  stage_2:
    keys_vacancy:
      - "Должность"
      - "Должность категория"
      - "Должность подкатегория"
      - "Профессиональная область"
      - "Список навыков"
      - "Описание"
    model_name: "gpt-4o-mini"
    model_name_embed: "text-embedding-3-large"
    prompt_experience: "Сделай краткое содержание опыта работы по данным в json.\njson:\n"
    system_prompt_experience: |
      Вы являетесь сотрудником HR. Ваша задача составить краткое содержание опыта кандидата по переданным
      данным. Данные передаются в json формате. Необходимо выделить кол-во лет опыта работы и основные
      сферы деятельности кандидата. Также определить его уровень по шкале: junior, middle, senior, lead, если
      это возможно определить из переданной информации. Не обращай внимание на ключ 'endDate'. Там
      содержится нерелевантная информация. Верни только краткое содержание. Не придумывай факты.
      Если указано только одно место работы, то нельзя определить кол-во лет опыта. Если вы не уверены
      в уровне кандидата, то не нужно додумывать.
    request_num_workers: 8
    keys_cv:
      - "Должность"
      - "Должность категория"
      - "Должность подкатегория"
      - "Профессиональная область"
      - "Список навыков"
      - "Зарплатные ожидания"
      - "Образование"
      - "Опыт"
      - "Описание"
    weights: [1.0, 1.0, 1.0, 1.0, 2.0]
    top_n: 10
