general:
  mode: "prod"
model:
  stage_1:
    days_filter_threshold: 90
    close_dist_threshold: 50
    text_features:
      - "Категория прав"
      - "address_short"
    cluster_match_features:
      - "Переезд"
      - "Адрес"
      - "date"
    weights: [1, 0.5, 3, 1]
    top_n_init: 100
    top_n: 20
  stage_2:
    keys_vacancy:
      - "Должность"
      - "Должность категория"
      - "Должность подкатегория"
      - "Профессиональная область"
      - "Список навыков"
      - "Знания"
      - "Опыт работы"
      - "Образование"
      - "Условия работы"
      - "Зарплата"
      - "Описание"
    model_name: "gpt-4o-mini"
    model_name_embed: "text-embedding-3-large"
    category_desc:
      знания: "Знания - это тот набор знаний, который кандидат должен иметь, или имеет."
      опыт работы: "Опыт работы - информация о количестве лет работы и занимаемых позициях."
      образование: "Образование - информация о уровне образования и его направлении."
      условия работы: "Условия работы - информация о условиях работы и бонусах."
      зарплата: "Зарплата - количество денег, которое предлагают кандидату, или кандидат ожидает."
      навыки: "Навыки - умения, которыми кандидат должен обладать."
    cats_find_vacancy: []
    cats_find_cv:
      - "навыки"
      - "знания"
    prompt_experience: "Сделай краткое содержание опыта работы по данным в json.\njson:\n"
    system_prompt_experience: |
      Вы являетесь сотрудником HR. Ваша задача составить краткое содержание опыта кандидата по переданным
      данным. Данные передаются в json формате. Необходимо выделить кол-во лет опыта работы и основные
      сферы деятельности кандидата. Также определить его уровень по шкале: junior, middle, senior, lead, если
      это возможно определить из переданной информации. Не обращай внимание на ключ 'endDate'. Там
      содержится нерелевантная информация. Верни только краткое содержание. Не придумывай факты.
      Если указано только одно место работы, то нельзя определить кол-во лет опыта. Если вы не уверены
      в уровне кандидата, то не нужно додумывать.
    prompt_info: "Описание:\n[description]\nВопрос: [question]\nОтвет:"
    question_vac: "Какие требования к категории '[query]' указаны в описании вакансии?"
    question_cv:  "Какие [query] указаны в описании кандидата на вакансию?"
    system_prompt_info: |
      Вы эксперт в найме персонала. Необходимо извлечь необходимые [query] из описания. После этого
      необходимо убрать пересечение с данными для удаления, если такие данные переданы.
      Затем вернуть результа как отдельное поле в json с ключом '[query]'.
      Не нужно придумывать того, чего нет в описании. Если релевантных данных нет, то необходимо
      вернуть значение 'Нет данных' для ключа '[query]'.
    request_num_workers: 8
    keys_cv:
      - "Должность"
      - "Должность категория"
      - "Должность подкатегория"
      - "Профессиональная область"
      - "Список навыков"
      - "Знания"
      - "Зарплата"
      - "Образование"
      - "Опыт работы"
      - "Условия работы"
      - "Описание"
    top_n: 10
    prompt_matching: "Оцени, насколько кандидат подходит на ваканчию по соответсвию данных характеристик.\nОписание кандидата:"
    system_prompt_matching: |
      Вы являетесь сотрудником HR. Ваша задача для вакансии найти наиболее подходящего кандидатата.
      Для этого необходимо сравнить описание вакансии и описание кандидата и выдать меру того,
      насколько кандидат подходит. Для этого нужно сравнить требования из вакансии и характеристики
      кандидата. Если требование из вакансии совпадает с характеристикой кандидата, то это увеличивает
      меру похожести. Если в описании вакансии или кандидата указано, что данных нет, то мера похожести
      должна быть 0.
      Мера похожести должна быть числом от 0 до 1.
      Приведу пример для Опыта работы:

      Описание вакансии:\nОпыт работы: 3 года.
      Описание кандидата:\nОпыт работы: более 4 лет.
      match_score = 1.0

      Описание вакансии:\nОпыт работы: 3 года.
      Описание кандидата:\nОпыт работы: не указан.
      match_score = 0.0

      Ответ необходимо вернуть в формате json c ключом 'match_score' (мера похожести).
      Не придумывай факты.\nОписание вакансии:
    feats_match:
      - Компетенции
      - Знания
      - Навыки
      - Тип занятости
      - График работы
    feats_match_prompt:
      - Опыт работы
      - Образование
    ranking_features:
      - Категория прав
      - Переезд
      - Адрес
      - date
      - Компетенции
      - Знания
      - Навыки
      - Тип занятости
      - График работы
      - Опыт работы
      - Образование
    sim_scores_names: []
    weights: [3.0, 1.0, 6.0, 1.5, 0.5, 0.25, 0.5, 0.5, 0.5, 0.25, 0.25]
